package com.nse.excelupload.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cell implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("cellName")
	private java.lang.String cellName;
	@org.kie.api.definition.type.Label("value")
	private double value;
	@org.kie.api.definition.type.Label("valid")
	private String valid;
	@org.kie.api.definition.type.Label(value = "validationMsg")
	private java.lang.String validationMsg;
	public Cell() {
	}

	public java.lang.String getCellName() {
		return this.cellName;
	}

	public void setCellName(java.lang.String cellName) {
		this.cellName = cellName;
	}

	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

	public java.lang.String getValid() {
		return this.valid;
	}

	public void setValid(java.lang.String valid) {
		this.valid = valid;
	}

	public java.lang.String getValidationMsg() {
		return this.validationMsg;
	}

	public void setValidationMsg(java.lang.String validationMsg) {
		this.validationMsg = validationMsg;
	}

	public Cell(java.lang.String cellName, double value,
			java.lang.String valid, java.lang.String validationMsg) {
		this.cellName = cellName;
		this.value = value;
		this.valid = valid;
		this.validationMsg = validationMsg;
	}

}